import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Loginbutton from "./loginbutton";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogOut from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session);
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {session ? (
            <span>
              화녕합니다 {session.user.name} <LogOut />{" "}
            </span>
          ) : (
            <Loginbutton></Loginbutton>
          )}
          <Link href="/write">작성</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
